// Weird moves can be overridden here.
const SPECIAL_MOVES = {
  splash: "The user splashes around dramatically. Nothing happens.",
  protect: "Until the start of its next turn, the user gains +5 AC and advantage on Dexterity saving throws. Once used, this move cannot be used again until the user completes another turn.",
  detect: "Until the start of its next turn, the user gains +5 AC and advantage on Dexterity saving throws. Once used, this move cannot be used again until the user completes another turn.",
  recover: "The user regains hit points equal to half its maximum hit points.",
  "soft-boiled": "The user regains hit points equal to half its maximum hit points.",
  "milk-drink": "The user regains hit points equal to half its maximum hit points.",
  rest: "The user falls Unconscious until the end of its next turn and regains half its maximum hit points. Poison, burns, paralysis, and similar conditions affecting it end.",
  substitute: "The user loses one-quarter of its maximum hit points and creates a substitute with that many hit points. Damage is dealt to the substitute before the user. The substitute disappears when reduced to 0 hit points.",
  "baton-pass": "The user switches places with an allied creature. Beneficial temporary effects currently affecting the user may transfer to that ally at the DM's discretion.",
  transform: "The user magically transforms into a creature it can see, copying its form and moves. Its own hit points and personality remain unchanged.",
  metronome: "Roll randomly for another Pokémon move. The user immediately uses that move.",
  "destiny-bond": "Until the start of the user's next turn, if another creature reduces the user to 0 hit points, that creature takes Necrotic damage equal to the user's maximum hit points.",
  "perish-song": "Creatures that can hear the song must make a WIS saving throw. On a failure, they are marked for doom. At the end of their third turn after hearing the song, they drop to 0 hit points unless the effect has ended or they have left the encounter.",
  "trick-room": "For 3 rounds, initiative order is reversed: creatures with lower initiative results act before creatures with higher results.",
  counter: "Reaction: When the user is hit by a physical attack, it makes an attack against the attacker. On a hit, the attack deals damage equal to the damage the user just took, up to the user's maximum hit points.",
  "mirror-coat": "Reaction: When the user is damaged by a special attack, it reflects psychic energy toward the attacker, dealing damage equal to the damage it just took, up to the user's maximum hit points.",
  endeavor: "The target must make a CON saving throw. On a failure, if it currently has more hit points than the user, its hit points are reduced to equal the user's current hit points.",
  "pain-split": "The user and target average their current hit points and each creature's hit points become that amount, never exceeding its maximum.",
  sketch: "The user permanently learns one move it has witnessed. It cannot use Sketch again after successfully copying a move.",
};
